#!/usr/bin/python

# ------------------------------------------------------------------------------
# 
# vis.py
# 
# Usage:   $ python  vis.py  /path/to/file.csvv  rgb/grayscale[default=rgb]  dims[default=224,224,3]
# 
# Use this script to visualize csv files generated by img_to_csv.py
# 
# ------------------------------------------------------------------------------

import matplotlib.pyplot as plt
import numpy as np
import sys

# Parse args

if len(sys.argv) not in [2,3,4]:
  print 'Use this script to visualize csv files generated by img_to_csv.py'
  print 
  print 'Usage:   $ python  vis.py  /path/to/file.csv  rgb/grayscale[default=rgb]  dims[default=224,224,3]'
  sys.exit(0)

file_path = sys.argv[1]

colormap  = 'rgb'
if len(sys.argv) > 2:
  colormap  = sys.argv[2]

dims = [224, 224, 3]
if len(sys.argv) == 4:
  dims_str = sys.argv[3].split(',')
  dims = []
  for dim in dims_str:
    dims.append(int(dim))

# Display image
if colormap == 'grayscale':
  x_image = np.genfromtxt(file_path, delimiter="\n").reshape(1, dims[0], dims[1], 1)
  imgplot = plt.imshow(x_image[0,:,:,0], cmap='gray')
else:
  x_image = np.genfromtxt(file_path, delimiter="\n").reshape(1, dims[2], dims[1], dims[0])
  x_image = np.transpose(x_image, [0, 2, 3, 1]).reshape(1, dims[0], dims[1], dims[2])
  imgplot = plt.imshow(x_image[0,:,:,:])

plt.show()
